# fly.toml app configuration file generated for todo-management-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-management-backend'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "http"
  timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
