[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
concurrency = 1
minInstances = 1
maxInstances = 1
